package main

var priorityMap = map[string]int{
	"none":     PRIORITY_NONE,
	"n":        PRIORITY_NONE,
	"low":      PRIORITY_LOW,
	"l":        PRIORITY_LOW,
	"medium":   PRIORITY_MED,
	"mid":      PRIORITY_MED,
	"m":        PRIORITY_MED,
	"high":     PRIORITY_HIGH,
	"hi":       PRIORITY_HIGH,
	"h":        PRIORITY_HIGH,
	"critical": PRIORITY_CRIT,
	"crit":     PRIORITY_CRIT,
	"c":        PRIORITY_CRIT,
}

var statusMap = map[int]string{
	STATUS_NEW:       "New",
	STATUS_INPROG:    "In progress",
	STATUS_HOLD:      "On hold",
	STATUS_COMPLETED: "Completed",
}

var verbMap = map[string]int{
	"add":      V_ADD,
	"a":        V_ADD,
	"complete": V_COMPLETE,
	"c":        V_COMPLETE,
	"count":    V_COUNT,
	"delete":   V_DELETE,
	"help":     V_HELP,
	"h":        V_HELP,
	"hold":     V_HOLD,
	"ho":       V_HOLD,
	"list":     V_LIST,
	"l":        V_LIST,
	"reopen":   V_REOPEN,
	"r":        V_REOPEN,
	"show":     V_SHOW,
	"s":        V_SHOW,
	"update":   V_UPDATE,
	"u":        V_UPDATE,
	"version":  V_VERSION,
	"v":        V_VERSION,
}
var argMap = map[string]int{
	"--all":         A_ALL,
	"-a":            A_ALL,
	"--comment":     A_COMMENT,
	"--completed":   A_COMPLETED,
	"-c":            A_COMPLETED,
	"-deleted":      A_DELETED,
	"--description": A_DESCRIPTION,
	"--desc":        A_DESCRIPTION,
	"--due":         A_DUE,
	"-d":            A_DUE,
	"--inprogress":  A_INPROGRESS,
	"-p":            A_INPROGRESS,
	"--new":         A_NEW,
	"-n":            A_NEW,
	"--onhold":      A_ONHOLD,
	"-h":            A_ONHOLD,
	"--open":        A_OPEN,
	"-o":            A_OPEN,
	"--overdue":     A_OVERDUE,
	"-od":           A_OVERDUE,
}
var kwargMap = map[string]int{
	"--due":      K_DATEDUE,
	"-d":         K_DATEDUE,
	"--id":       K_ID,
	"--parent":   K_PARENT,
	"--priority": K_PRIORITY,
	"--pty":      K_PRIORITY,
	"--project":  K_PROJECT,
	"--proj":     K_PROJECT,
	"-p":         K_PROJECT,
	"--summary":  K_SUMMARY,
	"-s":         K_SUMMARY,
}
var validatorMap = map[int]func(*Parser, string) (interface{}, error){
	K_DATEDUE:  (*Parser).validateDate,
	K_ID:       (*Parser).validateInt,
	K_PARENT:   (*Parser).validateInt,
	K_PRIORITY: (*Parser).validatePriority,
	K_PROJECT:  (*Parser).validateProject,
	K_SUMMARY:  (*Parser).validateSummary,
}
